# ===============================
# Persistent Volume for MongoDB (AKS with Azure Disk)
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default

---
# ===============================
# MongoDB Deployment & Service
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

# ===============================
# Notification API Deployment & Service
# ===============================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationapi
  template:
    metadata:
      labels:
        app: notificationapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: notificationapi
          image: matheuandrade.azurecr.io/notificationapi:v1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: MongoDB__ConnectionString
              value: mongodb://mongo:27017
            - name: MongoDB__DatabaseName
              value: MyAppDb
            - name: MongoDB__CollectionName
              value: Notifications
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi
spec:
  type: ClusterIP
  selector:
    app: notificationapi
  ports:
    - port: 80
      targetPort: 80

# ===============================
# Shopping API Deployment & Service
# ===============================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: shoppingapi
          image: matheuandrade.azurecr.io/shoppingapi:v1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: MongoDB__ConnectionString
              value: mongodb://mongo:27017
            - name: MongoDB__DatabaseName
              value: MyAppDb
            - name: MongoDB__CollectionName
              value: Users
            - name: NotificationService__BaseUrl
              value: http://notificationapi
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi
spec:
  type: LoadBalancer
  selector:
    app: shoppingapi
  ports:
    - port: 80
      targetPort: 80
