version: '3.8'

services:
  shoppingapi:
    build:
      context: ./src/Shopping.Api
      dockerfile: Dockerfile
    image: shoppingapi
    container_name: shoppingapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=MyAppDb
      - MongoDB__CollectionName=Users
      - NotificationService__BaseUrl=http://notificationapi
    depends_on:
      - mongo
      - notificationapi
    networks:
      - app-network

  notificationapi:
    build:
      context: ./src/Notification.Api
      dockerfile: Dockerfile
    image: notificationapi
    container_name: notificationapi
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=MyAppDb
      - MongoDB__CollectionName=Notifications
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
