version: '3.8'

services:
  shoppingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./src/Shopping.Api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    command: dotnet watch run --urls http://+:80
    ports:
      - "5000:80"

  notificationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./src/Notification.Api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    command: dotnet watch run --urls http://+:80
    ports:
      - "5001:80"

  mongo:
    ports:
      - "27017:27017"
