name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ou a branch que você quiser monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Instala o .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' # ajuste conforme sua versão

      # 3. Restaura dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build da aplicação
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # 5. Publica o projeto (gera artefatos prontos para o Docker)
      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      # 6. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Build e push da imagem
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoppingapi:latest
